Fix several related issues at once
- update github actions workflows
  - fix path for quiz/__init__.py
  - add additional checks for token
  - add different method for secret variable
- move app.py and __init__.py to quiz directory as a module
- fix some template location issues after quiz module

diff --git a/.github/workflows/update_build_date.yaml b/.github/workflows/update_build_date.yaml
--- a/.github/workflows/update_build_date.yaml
+++ b/.github/workflows/update_build_date.yaml
@@ -17,20 +17,52 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
-      
+
+    - name: Verify PAT Secret
+      env:
+        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
+      run: |
+        if [ -z "${ACTIONS_PAT}" ]; then
+          echo "Error: Unable to find the PAT secret for permissions."
+          exit 1
+        fi
+
     - name: Update build date
       run: |
-        echo -n "Before: " && grep "^__build_date__" __init__.py
+        echo -n "Before: " && grep "^__build_date__" quiz/__init__.py
         current_date=$(date +'%Y-%m-%d-%H-%M-%S')
-        sed -i "s/__build_date__ = .*/__build_date__ = '$current_date'/g" __init__.py
-        echo -n "After:  " && grep "^__build_date__" __init__.py
+        sed -i "s/__build_date__ = .*/__build_date__ = '$current_date'/g" quiz/__init__.py
+        echo -n "After:  " && grep "^__build_date__" quiz/__init__.py
 
     - name: Commit and push build date update
       env:
-        TOKEN: ${{ secrets.ACTIONS_PAT }}
+        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
       run: |
+        if [ -z "${ACTIONS_PAT}" ]; then
+          echo "Error: Aborting with missing PAT secret."
+          exit 1
+        fi
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
-        git add __init__.py
+        git add quiz/__init__.py
         git commit -m "Update build date to $current_date"
-        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
+        git push https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
+
+
+
+
+
+name: Debug Actions PAT
+
+on:
+  push:
+    branches:
+      - main
+
+jobs:
+  debug_secret:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
