Fix several related issues at once
- update github actions workflows
  - fix path for quiz/__init__.py
  - add additional checks for token
  - add different method for secret variable
- move app.py and __init__.py to quiz directory as a module
- fix some template location issues after quiz module

diff --git a/.github/workflows/version_increment.yaml b/.github/workflows/version_increment.yaml
--- a/.github/workflows/version_increment.yaml
+++ b/.github/workflows/version_increment.yaml
@@ -16,13 +16,22 @@ jobs:
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
-      
+
+    - name: Verify PAT Secret
+      env:
+        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
+      run: |
+        if [ -z "${ACTIONS_PAT}" ]; then
+          echo "Error: Unable to find the PAT secret for permissions."
+          exit 1
+        fi
+
     - name: Increment version patch number
       id: increment_version
       run: |
         # Extract the current version
-        current_version=$(awk -F'[(), ]+' '/^__version_info__/ {print $3 "." $4 "." $5}' __init__.py)
-        #grep "^__version_info__" __init__.py
+        current_version=$(awk -F'[(), ]+' '/^__version_info__/ {print $3 "." $4 "." $5}' quiz/__init__.py)
+        #grep "^__version_info__" quiz/__init__.py
         #echo $current_version
 
         # Ensure current_version is correctly extracted
@@ -43,17 +52,21 @@ jobs:
         new_version_info=$(echo $new_version | awk -F. '{printf("\x27%d\x27, \x27%d\x27, \x27%d\x27", $1, $2, $3)}')
         #echo $new_version_info
 
-        # Update the __init__.py file with the new version info
-        echo -n "Before: " && grep "^__version_info__" __init__.py
-        sed -i -E "s/^__version_info__ = \(.*\)/__version_info__ = \($new_version_info\)/" __init__.py
-        echo -n "After:  " && grep "^__version_info__" __init__.py
+        # Update the quiz/__init__.py file with the new version info
+        echo -n "Before: " && grep "^__version_info__" quiz/__init__.py
+        sed -i -E "s/^__version_info__ = \(.*\)/__version_info__ = \($new_version_info\)/" quiz/__init__.py
+        echo -n "After:  " && grep "^__version_info__" quiz/__init__.py
 
     - name: Commit and push version increment
       env:
-        TOKEN: ${{ secrets.ACTIONS_PAT }}
+        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
       run: |
+        if [ -z "${ACTIONS_PAT}" ]; then
+          echo "Error: Aborting with missing PAT secret."
+          exit 1
+        fi
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
-        git add __init__.py
+        git add quiz/__init__.py
         git commit -m "Increment version patch number"
-        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
+        git push https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
